language: python

python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"

install:
    - pip install -U pytest>=2.8 flake8>=3.0
    - python setup.py install

script:
    - py.test --flake8 --flake8-ignore=E128
